### ISSUE TITLE
Respect yarn.lock

### ISSUE THREAD

**Issue by akoenig** [coollabsio/coolify#102]
First of all, you're doing an awesome job with coolify, @andrasbacsai! 🎉 It is such a great project!

I'm currently evaluating `coolify` in the context of providing tenant-specific deployment environments for our clients and it looks awesome so far! I stumbled upon one aspect which I would like to share: When deploying a Next.js based application the DX is excellent and indeed similar to something like Vercel. When deploying the application though, it utilizes the correct buildpack, but assumes that `npm` is getting used:

![Screenshot 2022-01-12 19 17 36](https://user-images.githubusercontent.com/224910/149199660-0e1da7d4-bbb4-4352-8a40-8f50db436fdb.png)

So it copies the `package*.json` files, but not the `yarn.lock` file which causes problems when the project is relying on yarn in general. It would be great if the buildpack would also copy the `yarn.lock` over.

As you can see, we established a workaround by configuring a `yarn install & yarn build` as the _build command_ in Coolify.

**Comment by andrasbacsai** [comment]
Thank you @akoenig! 🙂 

That is an excellent suggestion, and I have no idea why I missed that! It will be corrected in v2, which comes out soon.

Wow! Good to hear that you are evaluating Coolify! 
V2 will have many new features; for example, you could deploy different applications/databases on various docker engines/networks (later on to Kubernetes), team management (all resources are assigned to a team so that you can separate different environments between different teams), or the most exciting one is that you can set a database instance to public with a simple button so that you can connect to it remotely, via your favorite client tool! I'm excited! 😁

**Comment by akoenig** [comment]
@andrasbacsai Wow! @andrasbacsai, V2 sounds awesome. I'm excited too!

Can't wait to test drive the release 🙂 Is it sufficient to use the `Dockerfile` in the branch or are there more steps involved for starting this release?

**Comment by andrasbacsai** [comment]
More steps. Well, less than for v1, but v2 is not compatible with v1. I totally changed the architecture for a good reason. 😄

**Comment by andrasbacsai** [comment]
v2 respects `yarn.lock`, `pnpm-lock.yaml` and `package-lock.json`! Thanks for the suggestion!
