### ISSUE TITLE
"reset your password from the login page with the `COOLIFY_SECRET_KEY` environment variable"

### ISSUE THREAD

**Issue by bohtho** [coollabsio/coolify#1020]
> You can always reset your password from the login page with the `COOLIFY_SECRET_KEY` environment variable located in `~/coolify/.env` file.

_Originally posted by @andrasbacsai in https://github.com/coollabsio/coolify/issues/212#issuecomment-1068137751_
            
How does this work ? I've tried to reset and empty the env-variable while restarting coolify but it still asks me to log in and gives me an authentication error.

EDIT: To be clear I have managed to reset the password via the install script again but was just wondering about this statement/mechanism.

**Comment by Pitasi** [comment]
I'm not sure what that message means but I wanted to reset my user password from the UI, here's what I did:

- from IAM section click on "Reset Password" button
- a toast saying "Password reset successfully. Please relogin to reset it." appears
- logout
- the login page now works as a "set your new password" so anything you put in the password field will log you in, and will be your new password

Since I spent 15 minutes trying to figure it out I thought might be useful for someone else 😁

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
