### ISSUE TITLE
[Bug]: after successfully installing the coolify server on my vps .. I got a inline message like this is your host link <myip>:3000 !! Then I have trying to open but itt's showing again and again like the site can't be reached :(( !! Please ry to help me (55min. aprox passed after installation) 

### ISSUE THREAD

**Issue by Borutosschool** [coollabsio/coolify#1103]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Example public repository

coolify

### Description

not satisfied bro !! 55 min. passed but the local host is not opening :(

### Steps To Reproduce

1. goto coolify ocal host and the site shwoing can't reached (local host error)

### Version

2.5.2

**Comment by zdarin** [comment]
same

**Comment by techydad05** [comment]
I know that in my case I am running v4 on a debian vm and when it finished installing it tells me to go the public IP of my host network. If I go to that IP since I am actually using that IP even though I have a static IP set in my vm which is not the same as my public IP It will not work. If I go to the static IP I have set for my vm it works fine.

**Comment by andrasbacsai** [comment]
Due to inactivity, I'm closing this issue. However, if the problem persists, please reopen the issue. Thanks!
