### ISSUE TITLE
[Bug] Deploy v3

### ISSUE THREAD

**Issue by ikbenignace** [coollabsio/coolify#1110]
Something is very unefficient here, once you stop an application, there is only 1 button, the "Deploy" button which wil build the application again which isn't neccesary, you should have a "Start" button which starts the latest build or a "Rebuild/Redeploy" button.

At this moment you are unable to just start the latest build.

**Comment by andrasbacsai** [comment]
In v4, if the image is already available locally (later on in a docker registry) it is just started without rebuilding. 

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
