### ISSUE TITLE
v3.12.32 is not on Docker Hub

### ISSUE THREAD

**Issue by welcoMattic** [coollabsio/coolify#1114]
According to https://hub.docker.com/r/coollabsio/coolify/tags?page=1&name=3.12.3, the v3.12.32 image is not on the hub.

**Comment by jenishngl** [comment]
yeah, seems strange

**Comment by andrasbacsai** [comment]
Yeah, I forgot to sync, but why do you need it on DockerHub? It is available on ghcr.io which is the default docker registry for a while.

**Comment by jenishngl** [comment]
> Yeah, I forgot to sync, but why do you need it on DockerHub? It is available on ghcr.io which is the default docker registry for a while.

I started checking coolify yesterday and it was failing to install on my raspberry pi. After a lot of struggle I finally installed it. Coolify is AMAZING BTW!! 

While looking through issues and articles, this was confusing since the installer said it was installing 3.12.32 while the same was missing in DockerHub. Only today i understood ghcr.io was the default registry. Anyways its always good to keep things in sync so that new folks find it easy 🙂

**Comment by bestony** [comment]
> Yeah, I forgot to sync, but why do you need it on DockerHub? It is available on ghcr.io which is the default docker registry for a while.

just like ghcr.io is slow in China Mainland, so i always use Mirror (mirror only mirror dockerhub ,not mirror ghcr).

**Comment by andrasbacsai** [comment]
> > Yeah, I forgot to sync, but why do you need it on DockerHub? It is available on ghcr.io which is the default docker registry for a while.
> 
> just like ghcr.io is slow in China Mainland, so i always use Mirror (mirror only mirror dockerhub ,not mirror ghcr).

Oh that is good to know!

Fixed. It is now synced.
