### ISSUE TITLE
[Bug]: v4 The port is occupied by the previous container of this application

### ISSUE THREAD

**Issue by lortonx** [coollabsio/coolify#1242]
### Description

![image](https://github.com/coollabsio/coolify/assets/13281000/b91a9a33-82a3-494e-971c-39a702d7e9e4)

When building the container, an error occurs stating that the port is already in use.
This happens when a port is forwarded to the system and the user uses “Restart” or “Force Redeploy”.

Proposal to add a checkbox switch/notification that during redeploy/restart the container will not be able to start because the port is busy. I also suggest automatically stopping the container if the port forwarded to the system is specified.

### Minimal Reproduction (if possible, example repository)

Just deploy the application with Ports Mappings, and then run a restart of the container / force redeploy, in the deployments menu you will receive a notification that the port is occupied (by the same application of the old version)

### Version

v4.0.0-beta.43 - v4.0.0-beta.44

**Comment by andrasbacsai** [comment]
Nice catch! Fixed in the upcoming version #1250 

Updated the helper description and also skipped the rolling update in case you have a port mapped to the host, so it won't cause an issue like this. 


![image](https://github.com/coollabsio/coolify/assets/5845193/35ef14a7-8fb3-4401-873a-efc633aba88a)
![image](https://github.com/coollabsio/coolify/assets/5845193/4f831463-1a70-4c6a-b6e4-a337c993f323)
