### ISSUE TITLE
[Bugfix] Certbot and domain problems

### ISSUE THREAD

**Issue by krystofrezac** [coollabsio/coolify#140]
I recently upgraded to version 2 and it's awesome but some things do not work and I think that all of them are connected (at least some of them). 
### Domain
When I try to set the domain in global settings there are two possible outcomes. 
- If the domain is only HTTP then it is successfully saved, but when I try to login from the new domain I get this error `Wrong password or email address.` and the email and password are 100% correct.
- If the domain is with HTTPS then the saving takes about one minute and then it fails. I think that it's because of certbot. Cerbot docker logs:
![DeepinScreenshot_select-area_20220216090556](https://user-images.githubusercontent.com/39591095/154222834-1a55ed76-fd85-4bb1-b2f0-51c8f92da77f.png)
 ### HTTPS for applications
Another problem is that anytime I set a domain of an application with HTTPS it does not generate an SSL certificate. This is probably connected to certbot too. Certbot docker logs:
![DeepinScreenshot_select-area_20220215231028](https://user-images.githubusercontent.com/39591095/154223400-9ef1822b-25e0-4d1a-901c-50948743ef06.png)

I had on the same system installed version 1 and there was no problem with any of this.
My OS: Ubuntu 20.04.3 LTS x86_64

**Comment by andrasbacsai** [comment]
Thanks for the report!

> If the domain is only HTTP then it is successfully saved, but when I try to login from the new domain I get this error Wrong password or email address. and the email and password are 100% correct.

This one is on me. It looks like the session cookie sets with `Secure` by default, but not on localhost, so that's why it does not come up during my tests. It will be fixed in the next version!

About the other SSL problems. I'm not sure if it's related to Coolify. Coolify only starts the helper container that verifies your DNS configurations and issues the certificate. Based on the error, it looks like Let's Encrypt tries to connect your server on port `9080` to verify that you are the owner of the domain. But it fails to connect.

Don't you have a firewall in front of your server? Or are you using `iptables/ufw` maybe that blocks connection on that port?

**Comment by krystofrezac** [comment]
Yes, it will be probably the firewall, I didn't realize it. But I reinstall the whole server and I found another bug. When I fill email and password to the first login page it is loading for a few seconds and then it only refreshes the page and I can't get to the app.

**Comment by andrasbacsai** [comment]
Yes, I found the issue. One of the dependencies the app used introduced a giant bug. I was fixed in the latest (`v2.0.13`). Unfortunately, you need to reinstall Coolify to get the latest update. Sorry about that!
