### ISSUE TITLE
[Bug]: new version available button not working

### ISSUE THREAD

**Issue by RayBB** [coollabsio/coolify#1626]
### Description

when I click the new version available button it says upgrading to 185 (from 183) however 10-20 minutes later it still says update is available.

I'm pretty sure this is because my instance is out of storage because when I looked the storage is full.

I'm not quite sure where in the logs to double check and find out what the exact error message is.

### Minimal Reproduction (if possible, example repository)

1. Create an instance on an older version
2. Fill up the storage on the device
3. Click the update button

### Version

v4.0.0-beta.183

**Comment by andrasbacsai** [comment]
If the server storage is full, Coolify cannot download the new image, so that is why it is not working. 

I will add an additional action, that Coolify tries to cleanup Docker related dangling stuff before initiating the upgrade + filesystem usage job changed from running every 10 mins to 5 mins.

But this does not make sure it can cleanup your server.

**Comment by RayBB** [comment]
@andrasbacsai thanks for addressing. It sounds like an improvement.
def not high priority now but maybe one day if there was a warning that it failed to upgrade because of storage that would be nice.
