### ISSUE TITLE
[Bug]: There is a deployment in progress (after deployment failure)

### ISSUE THREAD

**Issue by maietta** [coollabsio/coolify#1720]
### Description

When deploying apps, I'm no longer getting the streamed view of the deployment process.

The streaming modal window sits empty.

![image](https://github.com/coollabsio/coolify/assets/11745020/09cc8c81-6394-4b8c-8f52-b60e3e062d34)

This will hang for a long time. 

But if I open a new UI view and try and deploy the app, it gives me:

"There is a deployment in progress"

### Minimal Reproduction (if possible, example repository)

I'm not even sure at this point.

I'm running Coolify on a Raspberry Pi 4 running Debian. Deployments were working yesterday with no issues, except I could not re-use domain names from deleted resources.

### Exception or Error

"There is a deployment in progress"

### Version

v4.0.0-beta.209

**Comment by NickDeLu** [comment]
how was this resolved?

**Comment by rohsyl** [comment]
Hi,

I'm having the same issue:

![image](https://github.com/user-attachments/assets/ca7f4338-4690-488c-973f-3aed5a88a7e9)

**Comment by ozgurkalan** [comment]
same here

**Comment by NickDeLu** [comment]
I think I figured it out, in my case if you are in the middle of a deployment and the coolify server is overloaded, it can get stuck. I am building and deploying docker compose containers in my case. When I try to deploy again using the coolify UI, this error appears. I have even tried to hit Clear Deployment Cache first, but that doesn't seem to have any affect. 

What I usually have to do is restart my server and then re ping my deployment webhook, it removes the error and the deployment usually works.

Probably an issue stemming from not allocating sufficient resources to coolify.

Has anyone checked the coolify API to see if there's any endpoints to managed the deployments in queue? Perhaps that's easier.

**Comment by ozgurkalan** [comment]
I solved mine too. Permission issue! 
I re-applied standard permissions and problem solved:
`
chown -R 9999:root /data/coolify
chmod -R 700 /data/coolify

`

**Comment by Iulian-Dragomirescu** [comment]
same here on v4 beta 318

**Comment by ozgurkalan** [comment]
> same here on v4 beta 319

try to stop every container, change the permissions and from coolify proxy restart...

```
docker stop $(docker ps -q)
chown -R 9999:root /data/coolify
chmod -R 700 /data/coolify

```

**Comment by Iulian-Dragomirescu** [comment]
I tried this, I solved it by deleting the application and reinstalling it

**Comment by alvarolozano** [comment]
That's because the database stores the status of the deployments, and it is not up to date with your project. In order to solve it, you should manually clear the registry from the database by following this steps.

# 1. Get the database container id

First, you'll need to find the coolify's database container
```shell
docker ps | grep coolify-db
```
![image](https://github.com/user-attachments/assets/ecfff273-0a6d-4395-af9b-1897140255d7)
grab the container ID (first column)

# 2. Access the command line

You should run the following command, replacing the ID with the one obtained in the 1st step
```bash
docker exec -it 4b14e88d77c9 bash
```

# 3. Remove registries from the table

To enter the database cli, enter the following command

```bash
psql -U coolify
```

And then, to remove the damaged registry, just execute the following command

```bash
DELETE FROM activity_log;
```

Now, exit the psql and container by using ``\q`` and then ``exit``. An now try to deploy the application again
