### ISSUE TITLE
[Bug]: Cannot restart proxy 

### ISSUE THREAD

**Issue by palzino** [coollabsio/coolify#1736]
### Description

Using ubuntu 22.04 and `apt install docker.io docker-compose`prior to installing coolify, traefik proxy cannot be restarted once it is turned off through the web ui. An invalid docker command is being used. 

### Minimal Reproduction (if possible, example repository)

If you disable traefik and select no proxy. then try to re-enable traefik an invalid docker command error is thrown.

### Exception or Error

`Creating required Docker Compose file.
Pulling docker image.
docker: 'compose' is not a docker command.
See 'docker --help'`

### Version

v4.0.0-beta.212

**Comment by ewertonls** [comment]
I was also getting this error, doing [these steps](https://docs.docker.com/compose/install/linux/#install-the-plugin-manually) fixed it for me: 
- install `docker-compose` to `${HOME}/.docker/cli-plugins` (home was root in my vps)
- and make it executable with `chmod +x ${HOME}/.docker/cli-plugins/docker-compose`

now if you run `docker compose` on terminal it will work as expected

install it manually or copy your docker-compose from your PATH to the `cli-plugins` folder, in my case the `docker-compose-plugin` didn't install because it is not available in ubuntu 22.04 apt

**Comment by andrasbacsai** [comment]
In the next version, I will add a "revalidate" button to the server view.

In the older version, the `docker compose` command is not checked by Coolify. So if Docker Engine + Compose were preinstalled on the server (and the old compose plugin was preinstalled), Coolify could not work as it requires the new compose plugin.

Server validation will install the correct versions automatically, and the "revalidate" button allows you to fix this issue with a button.
