### ISSUE TITLE
[Bug]: Using predefined network does not work

### ISSUE THREAD

**Issue by jonfriesen** [coollabsio/coolify#1777]
### Description

When setting up a N8N Sqlite instance, during the creation I selected the destination network I wanted to add N8n too. Before launching for the first time, I selected `Connect to Predefined Networks` and then started the stack. During the startup a new docker network was created where N8n is located.

<img width="1050" alt="image" src="https://github.com/coollabsio/coolify/assets/2105302/156f1d6d-15c1-4d27-bf8b-670e4684cec2">

### Minimal Reproduction (if possible, example repository)

1. Add a new N8N resource to a project
2. Select any server
3. Select a destination (eg. `coolify`)
4. Check the `Connect To Predefined Network` slider:
<img width="408" alt="image" src="https://github.com/coollabsio/coolify/assets/2105302/d60645be-1e00-480d-9f8e-f6ae64331191">

5. Click `Deploy`

Note, that even though we selected a destination and set the `Connect To Predefined Network` slider the service still creates a network when starting up. 

<img width="493" alt="image" src="https://github.com/coollabsio/coolify/assets/2105302/9e4523e0-72a4-435b-9a69-e1c3eba466db">

### Version

v4.0.0-beta.224

**Comment by andrasbacsai** [comment]
Yes, this functions as intended. If you attempt to link two services with the same name within a single network, it can lead to network problems because they share the same internal DNS. When you try to connect to one of them, the Docker network will round-robin you to one of them.

That is why, a separate network is created. 

`Connect To Predefined Network` is there to be able to connect from other services, with the custom internal hostname, which is in your case is `n8n-u8cgos4`.
