### ISSUE TITLE
[Bug]: Healthcheck configuration prevents resource access

### ISSUE THREAD

**Issue by DiiiaZoTe** [coollabsio/coolify#1830]
### Description

For git repo deployments, when the healthcheck is enabled, the resource is unavailable (404) until the first healthcheck kicks in.
Meaning this is fine if the healthcheck is set to a few seconds interval. However let's say you set it to 300 (5 minutes), your resource is unavailable for 5 minute before the first healthcheck hits.

A fix would be to have a healthcheck hit automatically 1 second after the resource is deployed, no matter your configuration.

For anyone with this issue to get your resource available, disable the healthcheck for now or change it to 5 seconds then re-deploy.

### Minimal Reproduction (if possible, example repository)

1. Create a git deployment for nextjs app
2. Change the healthcheck configuration to a bigger interval
3. Deploy the app
4. Try to access the app, it will not let you until the first healthcheck hits

### Version

v4.0.0-beta.236

**Comment by LockeAG** [comment]
I have noticed that my app becomes unresponsive and displays an error 404 due to the health check, especially in Next.js apps. 

After the initial deployment, I saw some warning logs in the app, and it became unhealthy. Later, it became completely unresponsive with the 404 error. 

This issue seems to be happening frequently. Disabling the Health Check seems to resolve it.

**Comment by andrasbacsai** [comment]
This is the default behavior of the Traefik proxy. It only allows connections to healthy containers, or if health check is disabled, it allows connections immediately.

I just found a bug in the rolling update feature. So in the next release, until the new app is healthy, the old one will stay. I introduced this bug a few days ago.
