### ISSUE TITLE
support for serverless

### ISSUE THREAD

**Issue by type-checker** [coollabsio/coolify#194]
Hi @andrasbacsai, great project. I've a query about supporting serverless for full-stack serverless apps. Does Coolify support serverless deployment and serverless functions and the serverless stacks like Lambda, API Gateway, Cognito, DynamoDB?

**Comment by andrasbacsai** [comment]
Thanks!

Serverless deployments and functions, definitely.

About serverless stack, do you mean integration with AWS? I know some open-source solutions for Lambda, but for others, I don't. Is there any?

**Comment by cupboard319** [comment]
@andrasbacsai Thank you for the response!

Is there any guide available for Serverless deployments and functions with Coolify for full-stack serverless apps? Also, is Coolify works like the same as Netlify to host static websites?

With serverless stacks means first having a cloud agnostic approach and then supporting the serverless stacks like Lambda, DynamoDB, etc. I'll check for open-source solution and will update soon.

**Comment by shubham-kaushal** [comment]
Hi @andrasbacsai, Coolify looks COOL!!

I'll try to add some insight on the above.

Serverless comes with cloud vendor lock-in and as Coolify is an alternative to Netlify, it has to be the cloud-agnostic approach. For serverless full-stack development and having a cloud-agnostic approach, it requires defining an Auth Layer, Storage Layer, Database Layer, CMS Layer, GraphQL APIs, etc. Listing some of the projects that may help in this path 
1. Infrastructure as Code for serverless deployment mechanisms like [Pulumi](https://github.com/pulumi/pulumi) (it's cloud-agnostic).
2. Define Auth Layer, so that it can integrate by defining as simple as a provider with any auth provider like Cognito, Okta, Ory, etc.
3. Similarly for Store Layer to support S3, and so on or for Database to support DynamoDB or ORM like Prisma.
4. For the CMS layer, something like this https://github.com/contentlayerdev/contentlayer to support any kind of CMS.
5. GraphQL APIs layer to develop serverless full-stack apps.
6. And lastly serverless functions.

Look forward to your view on this.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
