### ISSUE TITLE
[Bug]: Coolify healthcheck fails when using "scratch" base Docker image

### ISSUE THREAD

**Issue by danawoodman** [coollabsio/coolify#2002]
### Description

It appears something with coolify's healthcheck's (perhaps a dependency in the built image?) makes it so using a `scratch` docker base image will always fail health checks whereas using something like `alpine` succeeds.

### Minimal Reproduction (if possible, example repository)

The following docker file pointing to a simple hello-world golang server fails health checks:

```dockerfile
# syntax=docker/dockerfile:1
FROM golang:1.22 as build
WORKDIR /app
COPY . .
RUN go build -o /server .

FROM scratch
COPY --from=build /server /server
EXPOSE 3000
CMD ["/server"]
```

Changing `scratch` to `alpine:latest` causes health checks to pass consistently. 

### Exception or Error

Health checks fail tho the actual health check doesn't output anything useful to troubleshoot this issue. Had to figure it out with trial and error.

### Version

v4.0.0-beta.258

**Comment by andrasbacsai** [comment]
If you use a Dockerfile (with or without git) or docker image-based deployments, the health check command is basically an `exit 0` because of the lack of curl or wget commands.

But it looks like the scratch does not like that as well.

As it is hard to determine the final image source, I suggest to simply turn off health checks (on the UI) or use alpine image instead.

**Comment by danawoodman** [comment]
I ended up just moving to using Alpine 👍
