### ISSUE TITLE
Upgrade coolify

### ISSUE THREAD

**Issue by csulit** [coollabsio/coolify#218]
How to safely upgrade coolify?

**Comment by jdbrice** [comment]
<img width="275" alt="Screen Shot 2022-03-16 at 7 54 47 " src="https://user-images.githubusercontent.com/6765220/158584535-fb1647e0-6682-4159-8f40-073aded102cb.png">

For me there is a pinkish-purple upgrade button on the toolbar. Sometimes it fails because of the docker rate limiting. But if you try again later it has always eventually succeeded for me. With v2 this has been "safe" - all my apps and containers keep running through the upgrade

**Comment by andrasbacsai** [comment]
If I publish a new version, that purple button appears on the side, and you just need to click on it. 

All apps/service/databases are not affected by the upgrade.
