### ISSUE TITLE
[Bug]: Blocking IP Access to Coolify server

### ISSUE THREAD

**Issue by luckycreationsindia** [coollabsio/coolify#2195]
### Description

I'm trying to block IP Address access of coolify via ufw but it's not blocking the out port 8000.

Am i missing something or this need to be configured somewhere in Coolify?

### Minimal Reproduction (if possible, example repository)

1. Block port 8000 using command `sudo ufw deny out 8000`
2. Try to access via Private or public ip (127.0.0.1:8000)

### Exception or Error

N/A

### Version

v4.0.0-beta.277

**Comment by andrasbacsai** [comment]
Docker and ufw are [incompatible](https://docs.docker.com/network/packet-filtering-firewalls/#docker-and-ufw) with eachother by default. You need to use `iptables`.

You need to use the `DOCKER-USER` chain, because that is executed before the docker engine rules.

So in your case, the command should look like: `iptables -D DOCKER-USER -p tcp -m tcp --dport 8000 -j DROP`

**Comment by luckycreationsindia** [comment]
For some reason iptables were not working on ubuntu (I tried to block 8000 everywhere I could including DOCKER, DOCKER-USER but not success). I removed DMZ from router and added port forwarding for port 80 and 443.
