### ISSUE TITLE
[Help]: How to add Chatwoot on Coolify using Docker

### ISSUE THREAD

**Issue by gyancarlodasilva** [coollabsio/coolify#2238]
### Description

I am trying to deploy Chatwoot on Coolify using Docker, but I am encountering issues during the process. Despite following the provided documentation and setup steps, the deployment fails with errors that I cannot resolve. I would appreciate guidance or a step-by-step tutorial on how to successfully deploy Chatwoot on Coolify using Docker.

### Minimal Reproduction (if possible, example repository)

Here are the steps I followed to reproduce the issue:

1. **Set up Coolify:**
   - Installed Coolify on a VPS following the official documentation.

2. **Create a new application:**
   - Selected "New Application" and chose "Docker Compose" as the deployment method.

3. **Configure Chatwoot:**
   - Used the provided Docker Compose file from the Chatwoot repository - https://www.chatwoot.com/docs/self-hosted/deployment/docker
   - Set environment variables for Chatwoot as per the official documentation.
   - Adjusted configuration to match Coolify's requirements.

4. **Deploy the application:**
   - Initiated the deployment process.

### Observed Issue
- The deployment fails with error messages related to container startup, rails execution.
- Logs indicate issues with database connections and missing environment variables, even though they were configured as per the documentation.

### Expected Behavior
- Successful deployment of Chatwoot on Coolify using Docker with all services running correctly.

### Version

v4.0.0-beta.283

**Comment by gvzq** [comment]
@gyancarlodasilva `Chatwoot` is already added in the resources since this PR: https://github.com/coollabsio/coolify/pull/2283:
![image](https://github.com/user-attachments/assets/22fb1078-a026-4c15-b8bc-033ad943c031)

However, there seems to be an issue in the default docker compose service stack.

In the Rails service: 
```
2024-07-19T16:40:49.875718372Z exec docker/entrypoints/rails.sh: exec format error
```

In the Sidekiq service:
```
2024-07-19T16:41:43.849492428Z exec /usr/local/bundle/bin/bundle: exec format error
```
cc: @andrasbacsai how did you test this service?

**Comment by gvzq** [comment]
I figured out my issue. Coolify is running in `arm64` so I changed the image to `chatwoot/chatwoot:docker-foss-arm64-ce`. I believe Docker has Rosetta to emulate images, but there's nothing regarding host architecture. 

Whoever got here because of the logs, you will need to change your docker-compose file to:

```
services:
  rails:
    image: 'chatwoot/chatwoot:docker-foss-arm64-ce'
  sidekiq:
    image: 'chatwoot/chatwoot:docker-foss-arm64-ce'
```

I found this log:
```
rails The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 
sidekiq The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 
```

**Comment by isaacfink** [comment]
I am not getting any errors but the service is still not accessible from the domain added, might be related though

**Comment by andrasbacsai** [comment]
The currently added Chatwoot service is for Intel/AMD based servers. I am still figuring out how to make difference between ARM and Intel/AMD based services in a good way.

I close this issue now as the workaround (changing the image) works.
