### ISSUE TITLE
[Bug]: Removing and re-inviting a user causes an invalid invitation link

### ISSUE THREAD

**Issue by ck-euan** [coollabsio/coolify#2249]
### Description

If you remove a team member and then try to invite them again, the invitation link doesn't work and will send them back to the login screen.

I had to invite a different email address for it to work.

It also generated a different link to usual, the ones that didn't work looked like:

https://example.com/invitations/0o04040gww8ycwkcg252s80cs8cw4s00

and then the links that did work looked like:

https://example.com/auth/link?token=eyJpdiI6InY4eUxZalYzcTQvRkZlRmp6Y1k9IiwibWFjIjoiNjQyMDViMzYzMTgxMWZlNjJhOGY4NzAyYzI4M2ViMzg1Nzk0MjZiYjlkOWU4YzJhNGEwjg0ZmUxMiIsInRhZyI6IiJ9

It seems like removing a team member doesn't actually delete their account?

### Minimal Reproduction (if possible, example repository)

1. Have a team member signed up already
2. Remove them via the /team/members page
3. Generate a new invite link for them
4. Observe that the link doesn't work

### Version

v4.0.0-beta.284

**Comment by andrasbacsai** [comment]
I cannot reproduce the issue.

The link with `/auth/link` is for users who are not registered in your instance.

The link with `/invitations` is for users who already have an account in your instance.

Removing a team member does not delete the actual user. Yes, all users have their own personal team created. Otherwise, if you remove the user and they have no other teams available, then the user will be unable to access the system.

There is a new `Admin View` in the latest version, which allows the users with root privileges to delete any user from their instance.

![image.png](https://uploads.linear.app/0fa98b19-e5f3-418f-abaf-f6d47b6f525f/f4b93ee7-68d3-4110-8017-fdc80b2309b4/c211fafa-779b-4508-8fa5-c83925977367?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzBmYTk4YjE5LWU1ZjMtNDE4Zi1hYmFmLWY2ZDQ3YjZmNTI1Zi9mNGI5M2VlNy02OGQzLTQxMTAtODAxNy1mZGM4MGIyMzA5YjQvYzIxMWZhZmEtNzc5Yi00NTA4LThmYTUtYzgzOTI1OTc3MzY3IiwiaWF0IjoxNzE2MzgxMTgwLCJleHAiOjMzMjg2OTQxMTgwfQ.q8heGoxEGjDFlnF2zL7sb0DOissapbRMSA8GIiqUM7w "=530x")

**Comment by ck-euan** [comment]
That's great thank you @andrasbacsai 

Can confirm after removing them via the new admin view I can re-invite properly :)
