### ISSUE TITLE
[Bug]: Supabase integration making unwanted calls to the network

### ISSUE THREAD

**Issue by orthdron** [coollabsio/coolify#2419]
### Description

I am running a coolify instance with only 1 thing installed at the moment, Supabase.
Used the default configuration with only kong connected to a domain name.
Received an abuse notice from my hosting provider (Hetzner).

Attached a screenshot below (erased IP address of originating host)
<img width="706" alt="image" src="https://github.com/coollabsio/coolify/assets/41769111/b64ce447-d53e-4d0a-8b2b-b310085d357b">

### Minimal Reproduction (if possible, example repository)

Install coolify on ubuntu 24.04
Point a domain name to coolify instance
Install supabase
link domain name to supabase kong

### Version

v4.0.0-beta.294

**Comment by peaklabs-dev** [comment]
I do not think this problem is directly related to Coolify. It could happen if your server specs are too low and there are a lot of retries, especially Supabase needs a lot of resources. Please make sure you have a proper firewall setup and also enough resources when hosting heavy applications like Supabase. Also I would need more reproduction steps to fix this if it recurs again. I hope this is fixed, if not feel free to reopen this issue or create a new one.
