### ISSUE TITLE
[Bug]: Installation/Update/ Auto Updates to a new version not working since 294 and performance suggestion

### ISSUE THREAD

**Issue by ayntk-ai** [coollabsio/coolify#2475]
### Description

Automatic or manual updates are not currently available.

### Minimal Reproduction (if possible, example repository)

1. Install a new coolify instance, it will install v4.0.0-beta.294 instead of the latest. 
2. Wait in the coolify instance, the update button will never appear.
3. If automatic updates are enabled, coolify will not update from 294 to the latest 297 version automatically

- [ ] Fix the version number in the CDN file: https://cdn.coollabs.io/coolify/versions.json 
- [ ] Suggestion: Automatic updates every 10 minutes is way too often for performance. Please give us 2 cron expressions we can use:
1. Check for updates cron (this specifies how often to check for updates, once every 12h is more than enough). If an update is found we see the update button in coolify
2. Auto update cron -> if auto update is enabled, this specifies how many times a day auto updates should be installed.

### Exception or Error

Coolify is stuck on v4.0.0-beta.294.

Workaround install Coolify like this: `curl -fsSL https://cdn.coollabs.io/coolify/install.sh | bash -s 4.0.0-beta.297 `

Ralted issues: https://github.com/coollabsio/coolify/issues/2459

### Version

v4.0.0-beta.294

**Comment by andrasbacsai** [comment]
Thanks for the PR. It was intentional that the update process wouldn't be triggered. I was testing out things before releasing to the wilderness.

**It should work now.**

The release process has two phases.

1. I push to `main`, make a release on Github.
2. I update [the file](https://cdn.coollabs.io/coolify/versions.json) on CDN.

Only after point 2, the upgrade will happen.
