### ISSUE TITLE
[Bug]: Changing redis image in redis database creation has no effect

### ISSUE THREAD

**Issue by penilabs-admin** [coollabsio/coolify#2686]
### Description

I want to use redis stack server, I changed the redis image in creation form to redis/redis-stack-server:7.4.0-rc1 but after deployment, the image i get is redis:7.2.5

### Minimal Reproduction (if possible, example repository)

Just try to create a redis db and change the image

### Version

v4.0.0-beta.306

**Comment by Vahor** [comment]
Are you still seeing this issue ?

I've just tested on v4.0.0-beta.323:
![image](https://github.com/user-attachments/assets/68745781-7b2b-41d0-af0d-4c08bfc2eac1)

log says 7.3.240 but I assume that's because it's a rc version?
![image](https://github.com/user-attachments/assets/1d901507-2aed-4916-a6b2-a4a71fb92a93)


and when doing an docker inspect, the correct image is used:
![image](https://github.com/user-attachments/assets/9c03c0df-02db-45a4-bdbe-e5ace68bc877)

**Comment by geofferyj** [comment]
Hello, so I tried to add redis-stack to enable time-series but when I connect, it doesn't include timeseries

![Image](https://github.com/user-attachments/assets/3b084449-276c-4c04-9bd7-cc2571d6ce38)

**Comment by geofferyj** [comment]
found a solution.

If you're using redis-stack, add the following to the configuration field in general tab
```bash
port 6379
daemonize no
loadmodule /opt/redis-stack/lib/rediscompat.so
loadmodule /opt/redis-stack/lib/redisearch.so
loadmodule /opt/redis-stack/lib/redistimeseries.so
loadmodule /opt/redis-stack/lib/rejson.so
loadmodule /opt/redis-stack/lib/redisbloom.so
loadmodule /opt/redis-stack/lib/redisgears.so v8-plugin-path /opt/redis-stack/lib/libredisgears_v8_plugin.so
```

these were gotten from `etc/redis-stack.conf` in the container.

**Comment by peaklabs-dev** [comment]
Since you got it working and the image changing works correctely, I will close this issue.
