### ISSUE TITLE
Guide for adding services

### ISSUE THREAD

**Issue by Soneji** [coollabsio/coolify#291]
Hi

It would be useful to have a guide or some info about how we can contribute common services to coolify. 

Like say for example I wanted to add a new service like https://umami.is analytics. 

I would like to be able to send a PR to coolify so these services can be used by many others :)

Thanks

**Comment by matheusfenolio** [comment]
We could have an option to add repos that add functionalities like CapRover. It can make things easier and let OSS owners to maintain their own service.

**Comment by andrasbacsai** [comment]
Added Unami.is and also a guide on how to add services to the [CONTRIBUTION.md](https://github.com/coollabsio/coolify/blob/main/CONTRIBUTING.md) guide.

**Comment by matbgn** [comment]
A solution like the one-click app repository of CapRover will be amazing since their is plenty of apps that can be simply added and reviewed by the community. The syntax is really easy and straight forward to add new services, surely the reason why their is so many app there: https://github.com/caprover/one-click-apps/tree/master/public/v4/apps

Any long term plan for this?

**Comment by compgeniuses** [comment]
i think this is something that should be looked at into more details, unless the developers only want the implementation of the said services to only be limited to the standard release cycles.

I understand there are some services which requires some things implemented on the software core to be more realistic, but this is also an approach that can be applied for coolify to make it "catch Up" on Services implementations

**Comment by andrasbacsai** [comment]
Services will be added to v4, but not 100% sure how - by template or not.

I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
