### ISSUE TITLE
[Bug]: Can't select S3 storage if created in a team other than root

### ISSUE THREAD

**Issue by 4xx22** [coollabsio/coolify#2967]
### Description

When an S3 Storage is created in a team other than the `Root team`, it cannot be selected for `Scheduled Backups`. To be able to select the storage, it must be recreated in the `Root team`.

I'm not sure if this is a bug or an intentional feature. If it's intentional, I think there should be an explanation in the settings indicating that the storage must be created in the Root team.

### Minimal Reproduction (if possible, example repository)

- Create a new team
- Create a S3 Storage on the new team
- Go to Instance Backup
- Select S3 Enabled
- The list will be empty/don't have the S3 Storage you just created

### Version

v4.0.0-beta.319

### Cloud?

- [ ] Yes
- [X] No

**Comment by peaklabs-dev** [comment]
This is intentional because instance backups are for the hole Coolify DB itself and you probably only want your root team to be able to backup you instance DB for security purposes and the root team cannot be deleted so this makes sense for now. Also, this is good for Coolify cloud because you do not want users backing up the DB themselves as it also contains sensitive data like other users emails etc..
