### ISSUE TITLE
[Bug]: Custom domain not working.

### ISSUE THREAD

**Issue by LupuC** [coollabsio/coolify#3349]
### Description

I've set up coolify on a hetzner vps, then, on cloudflare, I added A dns pointing to the ip of the vps/ app, with the cname: coolify.
On the coolify app, in settings, I added the https://coolify.domain.com, but it seems to not working.

### Minimal Reproduction (if possible, example repository)

Fresh install, nothing else added.

### Version

v4.0.0-beta.329

### Cloud?

- [ ] Yes
- [X] No

**Comment by fcpauldiaz** [comment]
is it a subdomain for coolify or for an app inside coolify? You only need an A record for coolify.

**Comment by fabieu** [comment]
If you are using a firewall in Hetzner Cloud, make sure to open port 80 and 443 as well. Since Coolify will use this for its internal proxy, which will resolve your domain name ([Reference](https://coolify.io/docs/knowledge-base/server/firewall/))

You need to set your SSL/TLS configuration to at least Full in your Cloudflare dashboard ([Documentation](https://developers.cloudflare.com/ssl/origin-configuration/ssl-modes/full/))

**Comment by fabieu** [comment]
This is not a bug, but rather a configuration issue.

**Comment by LupuC** [comment]
> You need to set your SSL/TLS configuration to at least Full in your Cloudflare dashboard

That is what was missing. Thank you!
