### ISSUE TITLE
[Bug]: 500  Something is not okay, are you okay? There has been an error, we are working on it.  Error: explode(): Argument #2 ($string) must be of type string, array given (View: /var/www/html/resources/views/livewire/project/application/configuration.blade.php)

### ISSUE THREAD

**Issue by kaiwei** [coollabsio/coolify#3688]
### Error Message and Logs

500 Something is not okay, are you okay? There has been an error, we are working on it. Error: explode(): Argument #2 ($string) must be of type string, array given (View: /var/www/html/resources/views/livewire/project/application/configuration.blade.php)

### Steps to Reproduce

1. Try to delete an environment in a project - "Error Environment has defined resources, please delete them first."
2. Try to delete the only solo defined resource - "500 Something is not okay, are you okay? There has been an error, we are working on it. Error: explode(): Argument #2 ($string) must be of type string, array given (View: /var/www/html/resources/views/livewire/project/application/configuration.blade.php)"
3. Unable to delete anything as a result

### Coolify Version

v4.0.0-beta.350

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Debian 12

**Comment by andrasbacsai** [comment]
Can you please check with v351?

**Comment by TheSuperfluousMan** [comment]
Something is not okay, are you okay?
There has been an error, we are working on it.

Error: Call to a member function isBackupSolutionAvailable() on null (View: /var/www/html/resources/views/livewire/project/service/index.blade.php)

When clicking 'settings' under services - not sure if related bug since also hitting some blade code. Will post new bug if not related (and apologies).

![image](https://github.com/user-attachments/assets/296e0b6c-3648-4839-be6d-dfbc67a9f85a)

**Comment by andrasbacsai** [comment]
That one will be fixed soon in the next release.
