### ISSUE TITLE
Private Forks

### ISSUE THREAD

**Issue by habibyuri** [coollabsio/coolify#407]
Hi,
I have this idea for a while and i thought that it might be a good fit for Coolify,
I will try try to explain it with an example,

An awesome app called [audiobookshelf](https://github.com/advplyr/audiobookshelf)
Maybe i would love to make fundamental changes to ui or something else but the owner / community doesn't agree, if I fork the repo it will always forces it to be public and if I clone it and republish the repo privately it will be a hassle to manage the updates ( especially for multiple projects ) as explained is this Gist :
https://gist.github.com/0xjac/85097472043b697ab57ba1b1c7530274

So what i'm suggesting is the possibility to manage something like this,
You just provide the repo you want to clone, coolify copies it into your profile privately and whenever there is a new update from the orignal repo coolify magically notifies you and you have the ability to push the new update to the private repo, and if there is a conflict it creates a new branch etc ...

What do you guys think ?

**Comment by vasani-arpit** [comment]
repo linking and CI CD can be done in coolify. the rest of the things like syncing up repo with upstream and tracking conflicts should be done manually. I think that's the standard. I have been doing this for several open source products. But when it comes to syncing and updating my fork I'd never do it automatically because I don't know what is coming in updates and in the case of enterprise where there are live users this is never advisable. 

I believe it will complexify the flow in which coolify currently setting up projects. If you can do it with simple toggle button in setting or something like it then it would be great. Feel free to create a PR or to discuss further here.
