### ISSUE TITLE
[Bug]: dockurr/macos & windows template is not running because of kvm

### ISSUE THREAD

**Issue by mhsayan** [coollabsio/coolify#4451]
### Error Message and Logs

With zero configuration, it will be able to install the service, but it will not be able to launch the service. In the log section, this message will always appear:

```
ERROR: KVM acceleration not available (device file missing), this will cause a major loss of performance.
ERROR: See the FAQ on how to diagnose the cause, or continue without KVM by setting KVM=N (not recommended).
```

### Steps to Reproduce

1. Install the service
2. After the deployment is finished, try starting the session using the FQDN
3. Check the deployment log

### Coolify Version

v4.0.0-beta.373

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 24.04.1 LTS

**Comment by peaklabs-dev** [comment]
Thanks for reporting and fixing. Since there is a problem with servers that do not have KVM support, as most servers are VPS servers  I think, I had to disable the template for now. Not sure how to fix it yet, probably a UI warning or something.
See this commit for more details. https://github.com/coollabsio/coolify/pull/4418/commits/428ba67cc0171a46b298f0f130bb9f44a634229d
