### ISSUE TITLE
Kubernetes integration

### ISSUE THREAD

**Issue by nkovacic** [coollabsio/coolify#45]
Would be great if coolify could be installed into a Kubernetes cluster so that application and databases could autoscale.
Is this currently supported?

**Comment by andrasbacsai** [comment]
Currently, it's not supported, but I would like to support Kubernetes in the future.

**Comment by itsezc** [comment]
@andrasbacsai any ETA on this?

**Comment by badlanguage** [comment]
Some considerations to keep in mind when bringing K8s integration on board, is multi tenancy on a namespace level, allowing for multiple "projects" (explained further on #77); another consideration is to take into account the limitations imposed by kubernetes (https://kubernetes.io/docs/concepts/policy/limit-range/) which _most_ Coolify instances will never hit this limit, there will be use cases where larger scale is required, so considerations should be made to accommodate this, by perhaps using a service mesh (Istio - as a single mesh) https://istio.io/latest/docs/ops/deployment/deployment-models/#single-mesh

**Comment by uirpp** [comment]
Hi @andrasbacsai, I was just searching for issue related to Kubernetes for Coolify and found this. It's been more than a year since this issue is created, wondering if you planned something for Kubernetes support.

**Is Kubernetes support to Coolify coming anytime soon?** 

The only feature that is becoming hurdle in adopting Coolify to use in production is not having support for High Availability. With Kubernetes support it would be perfect to use Coolify. Coming from Caprover (which supports Docker Swarm) and Tsuru (which supports Kubernetes), I can say Coolify is lacking only in High Availability feature.

Look forward to your response.
Thanks!

**Comment by Wulfheart** [comment]
I think it is still planned. At least according to the homepage. 

If Kubernetes was supported it would be really awesome as I then think that Coolify could grow with me.

**Comment by rgstephens** [comment]
Does the work in progress for k8s mean documentation and/or a helm chart?

**Comment by RyzeNGrind** [comment]
Is there anyway we can experiment and test? Would be nice to test this on arm64/amd64 hybrid cloud baremetal lab.

**Comment by SaadBazaz** [comment]
I'm aiming to part ways from CapRover to Coolify, due to Docker-Compose support and the sexy UI.
But I'm stuck at the installation screen:
```
Coolify does not support Docker Swarm yet. Please use a non-swarm compatible version of Docker.
```

This is a no-no :(

Here are some things I'll miss from CapRover:
- One-Click Apps: A lifesaver. Discovered vital tools from there.
- NetData Stats: A quick dashboard about CPU usage + memory will also do.
- Domain Management: redirecting my paid domain to Caprover was pretty easy. It also gave each app a subdomain.

Seeing these in Coolify would be great, it'd make the transition much easier.

**Comment by Wulfheart** [comment]
But it is only deploying as far as I can see. Nothing about scheduling and restarting etc.

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to a different platform. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.

**Comment by JamesTryand** [comment]
What platform?

**Comment by johnstonmatt** [comment]
Here's a `New Feature` Discussion: https://github.com/coollabsio/coolify/discussions/2455
