### ISSUE TITLE
[Bug]: every deploy causes all services and websites on self-hosted to go down with `timeout error`, and after 10min, it all comes back

### ISSUE THREAD

**Issue by shsunmoonlee** [coollabsio/coolify#4664]
### Error Message and Logs

every deploy causes all services and websites on self-hosted to go down with `timeout error`, and after 10min, it all comes back

### Steps to Reproduce

1. Self Host it on ubuntu 
2. host 5 nextjs apps with 2 supabase
3. deploy your 6th nextjs app
4. You'll see build get stuck and see it loses connection. All existing services also lose connection 
5.  after 10min, deployment finishes, and all existing services all comes back online

### Coolify Version

latest

### Are you using Coolify Cloud?

No (self-hosted)

### Operating System and Version (self-hosted)

Ubuntu 22.04

**Comment by tamasori** [comment]
@shsunmoonlee Hey! I had the same problem, exactly with NextJs. Next.Js is demanding during builds, and how demanding it is depends on your application as well. It turns out, the server just overloads itself, in our case the CPU couldn't handle anything else during a build. We upgraded our server, and now its not a problem anymore. I would suggest to have a look at your server usage while building, and if it peaks, it might be your problem too!
