### ISSUE TITLE
MacOs support

### ISSUE THREAD

**Issue by xisli** [coollabsio/coolify#492]
Is there a way to run it on Mac?

**Comment by andrasbacsai** [comment]
Hey, would you like to run the development or production version?

**Comment by xisli** [comment]
Development.

**Comment by ctwhome** [comment]
Production in my case, i do have a broken screen macbook pro that serves as a server, and i'd love to be able to use it there. So far i didn't manage to install Ubuntu server on it due to T2 chip and other restrictions

**Comment by ctwhome** [comment]
Using Curl instead of wget works to. Download install.sh:
curl https://get.coollabs.io/coolify/install.sh -o install.sh; sudo bash ./install.sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- -100 11667  100 11667    0     0  55293      0 --:--:-- --:--:-- --:--:-- 55293

cat: /proc/sys/kernel/random/uuid: No such file or directory

**Comment by ctwhome** [comment]
@andrasbacsai where is `install.sh` file located?

**Comment by edmsamuel** [comment]
where need to be located? :)
