### ISSUE TITLE
[Feature]: Allow Docker Swarm as destination

### ISSUE THREAD

**Issue by tiero** [coollabsio/coolify#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Summary

Improve scalability using multiple host machines to serve the same instance via Docker Swarm

### Why should this be worked on?

Scaling vertically the single host where coolify is deployed works fine but has some upper bound, where docker swarm allow the user to manage multiple containers deployed across multiple hosts machines.

**Comment by FranciscoMendes10866** [comment]
I share the same opinion, I think it would be interesting to be able to add worker nodes and then increase/decrease the number of instances of an app.

**Comment by maietta** [comment]
My two cents:

I wanted Traefik with Wildcard SSL's for all domains using Traefik's DNS plugin, with later ability to write my own plugin for my own self-hosted Authoriative nameservers. I want to write a tool to listen to changes in Traefik and update the IP's of any A records to match the correct nodes where servers are deployed. Since the DNS servers would live on the swarm clusters (syncronized as well), then I could enjoy near real-time DNS resolution by simply pointing all my domains to my own name servers.

I recently started playing around with Docker Swarm and Traefik for deploying service stacks and was building around this concept for my own deployment system until I discovered Coolify today while researching something totally unrelated. I tried to install Coolify on a Docker host in Swarm mode and saw that I cannot do that-- so I am now digging into how I could help solve this problem. Apps couple easily be deployed to a swarm using the `docker stack deploy` using the `docker context use` method to target a docker swarm. (Even if that Docker host node is a single node in a swarm). All it it takes to add Swarm Mode is a simple `docker swarm init`, even if you don't plan on adding more nodes. That would offer the ability to deploy apps as service stacks in a consistent way for single node or multi node swarms.

The `docker context` command and engine API gives us access to deploy service stacks to destination swarms. Running the deployment from a container for each deployment could help with isolating context switching. Adding a remote swarm is easy using the `docker context`.

Deploy the proxy.yml to all nodes in the cluster from any manager node in the swarm:

proxy.yml
```
# docker stack deploy -c  proxy.yml proxy

version: "3.8"

services:

  traefik:
    image: traefik:v2.4
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VULTR_API_KEY=<API_KEY>
    command:
#      - --log.level=DEBUG
#      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.swarmMode=true
      - --providers.docker.watch=true
      - --providers.docker.exposedByDefault=true
      
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
#      - --entrypoints.web.http.redirections.entrypoint.scheme=https

      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.websecure.http.tls.certResolver=myresolver
      
      - --certificatesresolvers.myresolver.acme.dnschallenge=true
      - --certificatesresolvers.myresolver.acme.dnschallenge.provider=vultr
      - --certificatesresolvers.myresolver.acme.email=<EMAIL_OF_SERVERADMIN>
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
#      - --certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/letsencrypt
    networks:
      - overlay
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

networks:
  overlay:

volumes:
  certs:
```

Then deploy any applications in the swarm like so:

maietta.yml
```
# docker stack deploy -c maietta.yml maietta-frontend

version: "3.8"

services:
  test:
    image: traefik/whoami
    labels:
      - traefik.http.routers.test.rule=Host(`test.maietta.app`)
#      - traefik.http.routers.ecstel.entrypoints=websecure
#      - traefik.http.routers.ecstel.tls.certresolver=myresolver
      - traefik.http.services.test.loadbalancer.server.port=80
    networks:
     - overlay
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
#        - traefik.enable=true
        - traefik.http.routers.test.rule=Host(`test.maietta.app`)
#        - traefik.http.routers.ecstel.entrypoints=websecure
#        - traefik.http.routers.ecstel.tls.certresolver=myresolver
        - traefik.http.services.test.loadbalancer.server.port=80
        - traefik.docker.network=test_overlay
        
networks:
  overlay:
```

**Comment by tiero** [comment]
@maietta I do also believe Docker Swarm is low-hanging fruit here. But I guess the plan of the maintainer is to use k8s and should be in the working as we speak.

But hey is open source, if you have experience with it, I will gladly donate/tip for a working PR that adds Docker Swarm to coolify

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
