### ISSUE TITLE
[Bug]: No build logs are output.

### ISSUE THREAD

**Issue by garth** [coollabsio/coolify#598]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

x

### Steps To Reproduce

Start a build from git, no logs get output, so you have no idea if it's working or not. The timer just keeps running.

![image](https://user-images.githubusercontent.com/4643/188720554-36ba571c-1c08-454a-bcbe-3782665dbadb.png)

### Version

3.9.1

**Comment by andrasbacsai** [comment]
You can always enable debug logging in the configuration/features section to see detailed logs about the builds. 

![image](https://user-images.githubusercontent.com/5845193/188821860-e7c21b65-465a-4626-ba40-7cf1f4bce32f.png)

It is disabled by default to prevent sensitive data (like ENV variables during the build) from being shown on the screen and saved to logs.

Your build probably takes too long, which is why there is no update in the UI. If it should be a few seconds, then it is a bug!

Let me know if debug logging shows more information about the build!
