### ISSUE TITLE
[Bug]: Coolify restrict domain names

### ISSUE THREAD

**Issue by daufinsyd** [coollabsio/coolify#824]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Example public repository

coolify

### Description

When I try to create a service with a domain name (for example local.0.) it won't accept it.
![image](https://user-images.githubusercontent.com/1218113/210563518-05e50984-f8af-48c8-b164-3585f83b4dfd.png)

### Steps To Reproduce

1. Create new service
2. in "URL (FQDN)" enter a non common domain name (ex: local.0)
3. try to save the service

### Version

3.12.8

**Comment by codesalatdev** [comment]
Coolify uses the regex `^https?://([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z]{2,}$` to validate FQDNs
https://github.com/coollabsio/coolify/blob/2e3c815e53a4b6dff8f422c0a0c62d84c4f5dad4/apps/ui/src/routes/applications/%5Bid%5D/index.svelte#L676

While a FQDN technically has a `.` as the rightmost character (between top-level and root-level), I'd suggest coolify should still require us to omit this, since `local.0` and `local.0.` mean the same thing here, which most definitely will cause issues. The database schema only seems to check for uniqueness and I can't find a syntax check in the API: https://github.com/coollabsio/coolify/blob/a58544b502efec9630c8eb4ceae73f7e8f089e7f/apps/api/src/routes/api/v1/applications/handlers.ts#L366

`^https?://([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z0-9]{1,}$` should be fine?

**Comment by daufinsyd** [comment]
Indeed
`^https?://([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z0-9]{1,}$` could do the tricks but I didn't understand why should coolify prevent user from using canonical FQDN like
`^https?://([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z0-9]{1,}\.?$`
Adding `\.?` would make `.` optional.

**Comment by codesalatdev** [comment]
> Indeed `^https?://([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z0-9]{1,}$` could do the tricks but I didn't understand why should coolify prevent user from using canonical FQDN like `^https?://([a-z0-9]+(-[a-z0-9]+)*\.)+[a-z0-9]{1,}\.?$` Adding `\.?` would make `.` optional.

Theoretically, you're right. The issue I am thinking of is that if we only change the regex, one could deploy two applications: one with `local.0` and the other with `local.0.` (api only checks for literal match with existing FQDNS). I imagine this would break something down the line (?)

**Comment by daufinsyd** [comment]
Indeed you're right, I didn't thought about it.

Well I'm not developing it but I believe it's better to not count on this side effect. Better allow the dot at the end and check if the fqdn is already taken, otherwise other bugs might arise.

For example, I found a "workaround", if you click on deploy (two times) instead of save, it will deploy even with "invalid" fqdn.

> This way, common mistakes in filling out that value could still be spotted easily, but we'd still have an option for uncommon domain names.
Yes I think that would be perfect :)

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
