### ISSUE TITLE
[Bug]: Docker Build Pack runs docker compose

### ISSUE THREAD

**Issue by Jan0707** [coollabsio/coolify#831]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Hi there 👋

I am currently trying to setup a simple docker container in Coolify. 

The way I understand the docker build pack it _should not_ be doing that. It should only be reading the one Dockerfile that I have specified, build it and run that _single_ container. Otherwise I would have chosen the docker compose build pack. 

Am I missing something ? Am I misunderstanding the intended use of the docker build pack ?

### Steps To Reproduce

I picked the docker build pack and pointed the settings to my `Dockerfile`. When I try to build it however, I see the following:

```
[22:11:26.253] Cloning foo/foo...
[22:11:28.072] Configuration changed
[22:11:29.400] Building production image...
[22:13:06.352] Command failed with exit code 15: docker compose --project-directory /tmp/build-sources/foo/foo/clcpau0o4000o9rnx7r9lepsb up -d
service "mongo" has neither an image nor a build context specified: invalid compose project
[22:13:06.363] {}
```

It seems that coolify picked up on the (existing, but in this context not usable) `docker-compose.yml` file that is also in this repository.

### Version

3.12.8

**Comment by andrasbacsai** [comment]
Hey 👋

Docker build pack is creating a `docker-compose.yaml` file because that is how I standardized the dynamic container definitions.

First, the dockerfile is used to build a docker image locally, and then docker-compose starts that docker image (based on your Dockerfile).

I've made some fixes in the upcoming version related to docker-compose; after I release it and you update, could you please recheck it?

If it still needs to be fixed, please provide a simple repository for testing because I tried several ones but could not replicate the issue.
