### ISSUE TITLE
[BUG] Docker system prune instead of docker image prune

### ISSUE THREAD

**Issue by simonorzel26** [coollabsio/coolify#869]
https://github.com/coollabsio/coolify/blob/75dd8946856d689a9b4e8e7a64ef16ee78dae429/apps/api/src/lib/common.ts#L1738

Even with V3 I still need to manually go into my server and `docker system prune`.  Would it be beneficial to add an option to prune system wide? 

If yes, I can go ahead and implement this.

**Comment by carvalholeo** [comment]
I've noticed that even I try to use "Cleanup storage" button, the space was not recovered.

So, I entered manually into my server and executed `docker image prune -a`. I recovered about 15 GB of my disk. Maybe, could have a option to execute this or an option list for what Ops command we want to run on the server.

**Comment by andrasbacsai** [comment]
`docker system prune` is not recommended because it could cause the deletion of images/networks that are not used but defined. 

For example, if you stop a database with Coolify (no container is running), `docker system prune` could delete the network (Destination inside Coolify).

I will fine-tune the function a bit.

**Comment by simonorzel26** [comment]
Ah I understand now
