### ISSUE TITLE
[Bug]: Docker Registries Gitlab

### ISSUE THREAD

**Issue by inluxc** [coollabsio/coolify#890]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I registered gitlab register in coolify
![colify](https://user-images.githubusercontent.com/584683/215170111-e4d488ae-19bd-477c-bb3b-8c7b5b759e98.png)
```

And i try to use an private container image in a docker-compose.yml from an application e tells its does not have access.

Error response from daemon: Head "https://registry.gitlab.com/v2/*************/*************/manifests/latest": denied: access forbidden
[16:17:18.975] Command failed with exit code 18: docker compose --project-directory /tmp/build-sources/************/*************/cldeq8iux004wagnsdd5ac3zw -f /tmp/build-sources/************/*************/cldeq8iux004wagnsdd5ac3zw/docker-compose.yml pull
app Pulling 
mysql Pulling 
redis Pulling 
app Error 
mysql Error 
redis Error 
Error response from daemon: Head "https://registry.gitlab.com/v2/promology/magento211/manifests/latest": denied: access forbidden
```

Do i need to do any thing else?
i tried the credentials locally and it worked fine.

### Steps To Reproduce

1. Create New Resource
2. New Application
3. Add repository from an integrated git app (gitlab.com)
4. Choose project, repo and version
5. And deploy

### Version

v3.12.17

**Comment by chez14** [comment]
I think this is because adding GitLab App and authenticating there, doesn't mean it will automatically generate deploy token for you.

 Can you try following steps to manually authenticate with GL Registry?
- Generate a Personal Access Token (from your profile settings page), or generate a new Deploy Token (in Project/Group Settings page).
- Go to Settings → Docker Registries
- Add new docker registries, use following setting:
  - URL: `registry.gitlab.com`
  - username: your username, if you're using personal access token, or; the token's username if you're using deploy token.
  - passowrd: the token.

Reference: https://docs.gitlab.com/ee/user/packages/container_registry/authenticate_with_container_registry.html

**Comment by inluxc** [comment]
But that's what i did, as you can see in the screenshot

**Comment by chez14** [comment]
Ah my bad, I didn't read the logs properly, sorry!

**Comment by ebreton** [comment]
Same issue here.

I also tried with an access token created with all available rights given in Gitlab.
Without any success (whereas the `docker login registry.gitlab.com` commands succeeds)

**Comment by andrasbacsai** [comment]
I'm closing this issue, because tracking features will be moved to GitHub discussions. Github issues will be only for bugs.

Version 4 is in full focus. v3 related issues will be closed, if it is not a critical bug.

Thanks for your understanding.
